server:
  port: 8092

spring:
  datasource:
    username: postgres
    password: ${PSSWRD}
    url: jdbc:postgresql://localhost:5432/ticket_service_db?currentSchema=ticket_service
  jpa:
    hibernate:
      dll-auto: update